services:

  angular:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "80:80"
      
  postgres:
    build:
      context: .
      dockerfile: /Database/Dockerfile
    image: "postgres-roseplus"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
       - db_volume:/data/postgres-volume
    ports:
      - "5432:5432"
    restart: unless-stopped
    
volumes:
    db_volume:
      external: true